"""Capture model outputs generated by a local notebook execution."""

from __future__ import annotations

import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "public" / "data" / "precomputed"
SNAPSHOT_CACHE = ROOT / "data" / "precomputed"


def main() -> None:
    if not GENERATED.exists():
        raise SystemExit("No generated cache found; execute the notebook locally first.")
    if SNAPSHOT_CACHE.exists():
        shutil.rmtree(SNAPSHOT_CACHE)
    shutil.copytree(GENERATED, SNAPSHOT_CACHE)
    print(f"Captured precomputed outputs in {SNAPSHOT_CACHE}")


if __name__ == "__main__":
    main()
